### PR TITLE
- Added pokemon nature to tooltips with config option

### PR DESCRIPTION
**Pull request by beerik94**
I added the pokemon nature since I am playing on a server with some friends and this was a heavily requested.
For this to be able to work in mp the server needs the mod as well.
This is currently being used on my server by me and my friends without any bugs or errors.

### CODE REVIEW

**Comment by beerik94** [comment]
Don't add this yet apparently the way I thought natures could be retrieved is not correct because after you catch the pokemon the nature is different. I'll reply again with a fix for this.

**Comment by beerik94** [comment]
Okay well I thought this was going to be an easy thing to add. Apparently the nature of a pokemon isn't send to the client before the pokemon is caught. So to be able to add this you need to send the nature in a packet to the client.
I don't have the time to dive deeper into this. Maybe if you ever have the time to look into this at least you know where to look I guess.

**Comment by Bletch1971** [comment]
The issue you encountered with the Client not having the data, it is only on the server, is why some of the pokemon information does not display correctly in TOP.
hwyla fixes the issue, but allowing you to pass information between the server and the client to be displayed.
If you have switched to using HWLYA, then I might be able to add it for you.

**Comment by beerik94** [comment]
Yes I switched to hwyla but even that one doesn't display nature correctly the way I added it in my pr. Maybe if it is done the way IVs and EVs are displayed it will be correct.

**Comment by Bletch1971** [comment]
Let me see what I can do to include it for HWLYA, not sure I will be able to do for TOP though.

**Comment by Bletch1971** [comment]
[PixelmonInformation-1.12.2-8.2.0-0.4.0.zip](https://github.com/Bletch1971/PixelmonInformation/files/7141510/PixelmonInformation-1.12.2-8.2.0-0.4.0.zip)
Here is a new version for Pixelmon 8.2 that contains your changes to add nature.

1. It works for both TOP and HYWLA in singleplayer
2. It only works in HYWLA for servers.

Are you able to test it for me and tell me if it works and you are happy with it?

**Comment by beerik94** [comment]
I have tested it and my client crashes while launching.
This is the crashlog https://pastebin.com/AZafWfga
My server starts without any problems.

**Comment by Bletch1971** [comment]
Are you able to tell me which version of Forge you are using. I am using the forge version that Pixelmon is using.

I had the same issue myself, but when I rebuilt the source with the version I gave you, the issue was fixed.

**Comment by Bletch1971** [comment]
Can you test this version please, let me know if it crashes for you.
[PixelmonInformation-1.12.2-8.2.0-0.4.0.zip](https://github.com/Bletch1971/PixelmonInformation/files/7147726/PixelmonInformation-1.12.2-8.2.0-0.4.0.zip)

**Comment by beerik94** [comment]
I am using forge 14.23.5.2854
The game launches without problems now.
In both SP and MP the nature shows correctly.
Thanks a lot for adding this feature.

**Comment by Bletch1971** [comment]
Thanks for helping to test the changes.
Have released to curseforge now.

**Pull request closed without merging**
